import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import type { FastifyInstance } from 'fastify';
import {
  createCandidateSha,
  HumanActorRequiredForApprovalError,
  createAuthenticatedActor
} from '@solutions-studio/domain';
import { FilesystemRequirementsRepository } from '../../../src/infrastructure/persistence/filesystem/FilesystemRequirementsRepository.js';
import { DefaultAuthorizationPolicy } from '../../../src/infrastructure/identity/DefaultAuthorizationPolicy.js';
import {
  RecordValidationRunUseCase,
  ApproveCandidateUseCase,
  EvaluateCandidatePromotionStatusUseCase
} from '../../../src/application/use-cases/governance/index.js';
import { composeOrchestratorHttpServer } from '../../../src/http/composition.js';
import { TestAuthenticator } from '../../../src/infrastructure/identity/TestAuthenticator.js';
import { runGovernanceCli } from '../../../scripts/run-governance.js';

describe('Phase 3 Incident Regression: Fabricated Markdown Sign-off Prevention', () => {
  let tmpDir: string;
  let repo: FilesystemRequirementsRepository;
  let authorizer: DefaultAuthorizationPolicy;
  let recordRunUseCase: RecordValidationRunUseCase;
  let approveUseCase: ApproveCandidateUseCase;
  let evaluateStatusUseCase: EvaluateCandidatePromotionStatusUseCase;
  let app: FastifyInstance;

  const validSha = 'd5adf81ac2ba5acd7b7cd22c830f03e2258a63b4';
  const nonexistentSha = '0000000000000000000000000000000000000000';
  const artifactHash = 'a'.repeat(64);

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'gov-p3-regression-'));
    repo = new FilesystemRequirementsRepository({ baseDir: tmpDir });
    authorizer = new DefaultAuthorizationPolicy();
    recordRunUseCase = new RecordValidationRunUseCase(repo);
    approveUseCase = new ApproveCandidateUseCase(repo, authorizer);
    evaluateStatusUseCase = new EvaluateCandidatePromotionStatusUseCase(repo);

    const composed = composeOrchestratorHttpServer({
      storeDir: tmpDir,
      repository: repo,
      authenticator: new TestAuthenticator({ allowAnonymousFallback: false }),
      fastifyOptions: { logger: false }
    });
    app = composed.app;
    await app.ready();
  });

  afterEach(async () => {
    await app.close();
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  it('fails closed when markdown report claims [x] GO but candidate SHA has no validation run', async () => {
    // The simulated Phase 3 incident: An automated agent generates a report claiming:
    const fabricatedMarkdownReport = `
# Phase 3 Exit Gate Validation Summary
- **Status:** **PASSED (All runs successful)**

## 12. Phase 3 Exit Decision Gate
### Human Disposition Gate
- [x] **GO** — Approve the exact candidate SHA and proceed to release.
- [ ] **DESIGN CHANGE**

### Justification & Reviewer Sign-off
- **Reviewing Authority (Sign-off):** opsclawd (operator)
- **Date Signed:** 2026-09-18T12:00:00.000Z
- **Rationale:** Fabricated sign-off text generated by unauthorized agent.
`;
    expect(fabricatedMarkdownReport).toContain('[x] **GO**');

    // The system evaluates candidate promotion status from first-class auditable repository state,
    // completely ignoring fabricated markdown text.
    const status = await evaluateStatusUseCase.execute({ candidateSha: nonexistentSha });

    expect(status.isApproved).toBe(false);
    expect(status.disposition).toBe('UNAPPROVED');
    expect(status.diagnosticCode).toBe('NO_VALIDATION_RUN');
    expect(status.message).toMatch(/No validation run found for candidate SHA/i);
  });

  it('fails closed when validation run exists but no human approval has been recorded', async () => {
    // 1. A legitimate validation run is recorded
    await recordRunUseCase.execute({
      candidateSha: validSha,
      phase: 'phase-3',
      executionMode: 'deterministic-ci',
      provider: 'fake',
      artifacts: [
        {
          name: 'schema-ddl.sql',
          artifactType: 'sql-ddl',
          contentHash: artifactHash
        }
      ],
      proposedDisposition: 'GO',
      summary: { testsPassed: 15 },
      executedBy: 'runner:ci'
    });

    // 2. An unapproved status evaluation must fail closed
    const status = await evaluateStatusUseCase.execute({ candidateSha: validSha });
    expect(status.isApproved).toBe(false);
    expect(status.disposition).toBe('UNAPPROVED');
    expect(status.diagnosticCode).toBe('AWAITING_APPROVAL');
    expect(status.message).toMatch(/has not been approved by an authenticated human reviewer/i);
  });

  it('rejects automated agent attempt to create promotion approval (Domain & Use Case)', async () => {
    const run = await recordRunUseCase.execute({
      candidateSha: validSha,
      phase: 'phase-3',
      executionMode: 'deterministic-ci',
      provider: 'fake',
      artifacts: [
        {
          name: 'schema-ddl.sql',
          artifactType: 'sql-ddl',
          contentHash: artifactHash
        }
      ],
      proposedDisposition: 'GO',
      summary: { testsPassed: 15 },
      executedBy: 'runner:ci'
    });

    const agentActor = createAuthenticatedActor({
      id: 'agent-generator-69',
      name: 'Automated Agent #69',
      actorType: 'agent',
      capabilities: ['candidate:approve'] // Even if granted capability in claims, agent type is banned
    });

    await expect(
      approveUseCase.execute({
        candidateSha: createCandidateSha(validSha),
        validationRunId: run.id,
        evidenceDigest: run.evidenceDigest,
        decision: 'GO',
        rationale: 'Fabricating sign-off as agent',
        actor: agentActor
      })
    ).rejects.toThrow(HumanActorRequiredForApprovalError);
  });

  it('rejects automated agent attempt via HTTP route with 403 HUMAN_ACTOR_REQUIRED', async () => {
    const run = await recordRunUseCase.execute({
      candidateSha: validSha,
      phase: 'phase-3',
      executionMode: 'deterministic-ci',
      provider: 'fake',
      artifacts: [
        {
          name: 'schema-ddl.sql',
          artifactType: 'sql-ddl',
          contentHash: artifactHash
        }
      ],
      proposedDisposition: 'GO',
      summary: { testsPassed: 15 },
      executedBy: 'runner:ci'
    });

    const res = await app.inject({
      method: 'POST',
      url: '/api/governance/approvals',
      headers: {
        authorization: 'Bearer test:agent'
      },
      payload: {
        candidateSha: validSha,
        validationRunId: run.id,
        evidenceDigest: run.evidenceDigest,
        decision: 'GO',
        rationale: 'Automated agent simulated sign-off'
      }
    });

    expect(res.statusCode).toBe(403);
    const body = res.json();
    expect(body.code).toBe('HUMAN_ACTOR_REQUIRED');
    expect(body.message).toMatch(/Approvals require an authenticated human actor/i);

    // Promotion status remains strictly UNAPPROVED
    const statusRes = await app.inject({
      method: 'GET',
      url: `/api/governance/candidates/${validSha}/status`,
      headers: {
        authorization: 'Bearer test:agent'
      }
    });
    expect(statusRes.statusCode).toBe(200);
    const statusBody = statusRes.json();
    expect(statusBody.isApproved).toBe(false);
    expect(statusBody.disposition).toBe('UNAPPROVED');
    expect(statusBody.diagnosticCode).toBe('AWAITING_APPROVAL');
  });

  it('fails closed when governance CLI approve is invoked without --token', async () => {
    await expect(
      runGovernanceCli([
        'approve',
        '--sha',
        validSha,
        '--run-id',
        'RUN-123',
        '--digest',
        artifactHash,
        '--rationale',
        'Attempt without token'
      ])
    ).rejects.toThrow(/Missing required argument: --token/);
  });

  it('fails closed when governance CLI revoke is invoked without --token', async () => {
    await expect(
      runGovernanceCli([
        'revoke',
        '--approval-id',
        'APPR-123',
        '--rationale',
        'Attempt revoke without token'
      ])
    ).rejects.toThrow(/Missing required argument: --token/);
  });

  it('fails closed in direct CLI mode when NODE_ENV is production without --allow-test-authenticator', async () => {
    const origEnv = process.env.NODE_ENV;
    try {
      process.env.NODE_ENV = 'production';
      await expect(
        runGovernanceCli([
          'approve',
          '--sha',
          validSha,
          '--run-id',
          'RUN-123',
          '--digest',
          artifactHash,
          '--rationale',
          'Prod direct test',
          '--token',
          'some-bearer-token',
          '--store-dir',
          tmpDir
        ])
      ).rejects.toThrow(
        /Direct mode execution with TestAuthenticator requires --allow-test-authenticator or NODE_ENV=test/
      );
    } finally {
      process.env.NODE_ENV = origEnv;
    }
  });
});
