import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import type { FastifyInstance } from 'fastify';
import {
  createRequirementId,
  createRequirementRevisionId,
  createPolicyConstraintId,
  createPolicyConstraintRevisionId,
  createEngineeringDecisionId,
  createRequirementsBaselineId,
  createReviewerId,
  createRequirementRevision,
  createPolicyConstraintRevision,
  createEngineeringDecision,
  now
} from '@solutions-studio/domain';
import {
  ProjectionRecordDtoSchema,
  RequirementsBaselineDtoSchema
} from '@solutions-studio/contracts';
import { FilesystemRequirementsRepository } from '../../src/infrastructure/persistence/filesystem/FilesystemRequirementsRepository.js';
import { ImmutableRecordConflictError } from '../../src/application/ports/persistence/IRequirementsRepository.js';
import { FakeGenerationGateway } from '../fakes/FakeGenerationGateway.js';
import { FakeMermaidLinterGateway } from '../fakes/FakeMermaidLinterGateway.js';
import { FakePrototypeValidatorGateway } from '../fakes/FakePrototypeValidatorGateway.js';
import { PGliteSqlValidatorAdapter } from '../../src/infrastructure/validation/PGliteSqlValidatorAdapter.js';
import { composeOrchestratorHttpServer } from '../../src/http/composition.js';

describe('Integration: SQL Schema Projection & PGlite Validation (Phase 3.2)', () => {
  let tempDir: string;
  let repo: FilesystemRequirementsRepository;
  let fakeGen: FakeGenerationGateway;
  let fakeLinter: FakeMermaidLinterGateway;
  let fakeProtoValidator: FakePrototypeValidatorGateway;
  let realSqlValidator: PGliteSqlValidatorAdapter;
  let app: FastifyInstance;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'sql-schema-integration-test-'));
    repo = new FilesystemRequirementsRepository({ baseDir: tempDir });
    fakeGen = new FakeGenerationGateway();
    fakeLinter = new FakeMermaidLinterGateway();
    fakeProtoValidator = new FakePrototypeValidatorGateway();
    realSqlValidator = new PGliteSqlValidatorAdapter();

    const composed = composeOrchestratorHttpServer({
      repository: repo,
      generationGateway: fakeGen,
      linterGateway: fakeLinter,
      prototypeValidatorGateway: fakeProtoValidator,
      sqlValidatorGateway: realSqlValidator
    });
    app = composed.app;
    await app.ready();
  });

  afterEach(async () => {
    await app.close();
    await fs.rm(tempDir, { recursive: true, force: true });
  });

  async function seedAuditedRequirement(reqId: string, revId: string, statement: string) {
    const rev = createRequirementRevision({
      id: createRequirementRevisionId(revId),
      requirementId: createRequirementId(reqId),
      revision: 1,
      statement,
      category: 'business-rule',
      origin: 'ASSUMED',
      reviewState: 'ACCEPTED',
      resolutionState: 'CLEAR',
      evidence: []
    });
    await repo.saveRequirementRevision(rev);

    await repo.appendReconciliationRecord({
      id: `rec-${revId}`,
      entityType: 'requirement',
      entityId: createRequirementId(reqId),
      requirementRevisionId: rev.id,
      action: 'ACCEPT',
      previousReviewState: undefined,
      newReviewState: 'ACCEPTED',
      rationale: 'Initial requirement audit accepted',
      recordedAt: now()
    });

    return rev;
  }

  it('generates a PostgreSQL schema projection from an immutable baseline, executes it in real PGlite, and preserves exact provenance (CONSUMER-69-AC-1, AC-6)', async () => {
    // 1. Seed requirement
    const req = await seedAuditedRequirement(
      'REQ-USER-001',
      'REQ-USER-001-R1',
      'Users must register with a unique email and hashed password'
    );

    // 2. Seed policy constraint
    const pol = createPolicyConstraintRevision({
      id: createPolicyConstraintRevisionId('POL-SEC-001-R1'),
      policyConstraintId: createPolicyConstraintId('POL-SEC-001'),
      revision: 1,
      statement: 'All relational tables must include audit columns created_at and updated_at',
      authorityReference: 'SEC-ENTERPRISE-STANDARD-v2',
      state: 'ACCEPTED',
      createdBy: 'SECURITY-OFFICER'
    });
    await repo.savePolicyConstraintRevision(pol);

    // 3. Seed accepted engineering decision
    const ed = createEngineeringDecision({
      id: createEngineeringDecisionId('ED-UUID-001'),
      baselineId: createRequirementsBaselineId('BASE-AUTH-001'),
      statement: 'Use UUID primary keys generated by gen_random_uuid()',
      rationale: 'Prevent ID enumeration and enable decentralized generation',
      state: 'ACCEPTED',
      createdBy: 'TECH-LEAD',
      acceptedBy: createReviewerId('ARCH-REVIEWER'),
      acceptedAt: now()
    });
    await repo.saveEngineeringDecision(ed);

    // 4. Create baseline
    const createBaseRes = await app.inject({
      method: 'POST',
      url: '/api/baselines',
      payload: {
        id: 'BASE-AUTH-001',
        requirementRevisions: [req.id],
        policyConstraintRevisions: [pol.id],
        createdBy: 'CHIEF-ARCHITECT'
      }
    });
    expect(createBaseRes.statusCode).toBe(200);

    // 5. Script fake generation with PostgreSQL-compatible DDL
    const validDdl = [
      '-- @baseline BASE-AUTH-001',
      '-- @requirements REQ-USER-001-R1',
      '-- @policy-constraints POL-SEC-001-R1',
      '-- @engineering-decisions ED-UUID-001',
      'CREATE TABLE users (',
      '  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
      '  email TEXT NOT NULL UNIQUE,',
      '  password_hash TEXT NOT NULL,',
      '  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),',
      '  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()',
      ');',
      'CREATE INDEX idx_users_email ON users(email);'
    ].join('\n');

    fakeGen.setDefaultResponse(`\`\`\`sql\n${validDdl}\n\`\`\``);

    // 6. Generate schema projection via POST
    const projRes = await app.inject({
      method: 'POST',
      url: '/api/baselines/BASE-AUTH-001/projections',
      payload: {
        artifactType: 'sql-schema'
      }
    });

    expect(projRes.statusCode).toBe(200);
    const body = projRes.json();
    const validatedDto = ProjectionRecordDtoSchema.parse(body);

    // Verify top-level provenance conservation (Finding 2)
    expect(validatedDto.baselineId).toBe('BASE-AUTH-001');
    expect(validatedDto.artifactType).toBe('sql-schema');
    expect(validatedDto.requirementRevisionIds).toEqual(['REQ-USER-001-R1']);
    expect(validatedDto.policyConstraintRevisionIds).toEqual(['POL-SEC-001-R1']);
    expect(validatedDto.engineeringDecisionIds).toEqual(['ED-UUID-001']);
    expect(validatedDto.content).toContain('CREATE TABLE users');
    expect(validatedDto.content).toContain('CREATE INDEX idx_users_email');

    // Verify metadata provenance
    expect(validatedDto.metadata.baselineId).toBe('BASE-AUTH-001');
    expect(validatedDto.metadata.requirementRevisionIds).toEqual(['REQ-USER-001-R1']);
    expect(validatedDto.metadata.policyConstraintRevisionIds).toEqual(['POL-SEC-001-R1']);
    expect(validatedDto.metadata.engineeringDecisionIds).toEqual(['ED-UUID-001']);
    expect(validatedDto.metadata.declaredProvenance.baselineId).toBe('BASE-AUTH-001');
    expect(validatedDto.metadata.declaredProvenance.requirementRevisionIds).toEqual([
      'REQ-USER-001-R1'
    ]);
    expect(validatedDto.metadata.declaredProvenance.policyConstraintRevisionIds).toEqual([
      'POL-SEC-001-R1'
    ]);
    expect(validatedDto.metadata.declaredProvenance.engineeringDecisionIds).toEqual([
      'ED-UUID-001'
    ]);
    expect(validatedDto.metadata.measuredVerification.repairsNeeded).toBe(0);
    expect(validatedDto.metadata.measuredVerification.attemptCount).toBe(1);
    expect(validatedDto.metadata.measuredVerification.contentHash).toBeDefined();

    // 7. Inspect projection via GET endpoint
    const getRes = await app.inject({
      method: 'GET',
      url: `/api/baselines/BASE-AUTH-001/projections/${validatedDto.id}`
    });
    expect(getRes.statusCode).toBe(200);
    const getDto = ProjectionRecordDtoSchema.parse(getRes.json());
    expect(getDto.id).toBe(validatedDto.id);
    expect(getDto.policyConstraintRevisionIds).toEqual(['POL-SEC-001-R1']);
    expect(getDto.engineeringDecisionIds).toEqual(['ED-UUID-001']);
  });

  it('repairs invalid SQL syntax through bounded closed-loop repair using real PGlite diagnostics (CONSUMER-69-AC-7)', async () => {
    const req = await seedAuditedRequirement(
      'REQ-ORDER-001',
      'REQ-ORDER-001-R1',
      'System records customer orders'
    );

    const createBaseRes = await app.inject({
      method: 'POST',
      url: '/api/baselines',
      payload: {
        id: 'BASE-ORDER-001',
        requirementRevisions: [req.id],
        createdBy: 'CHIEF-ARCHITECT'
      }
    });
    expect(createBaseRes.statusCode).toBe(200);

    // Attempt 0: Invalid SQL syntax (CREAT TABL)
    const brokenDdl = [
      '-- @baseline BASE-ORDER-001',
      '-- @requirements REQ-ORDER-001-R1',
      'CREAT TABL orders (id SERIAL PRIMARY KEY, total NUMERIC(10,2));'
    ].join('\n');

    // Attempt 1: Valid SQL syntax
    const fixedDdl = [
      '-- @baseline BASE-ORDER-001',
      '-- @requirements REQ-ORDER-001-R1',
      'CREATE TABLE orders (id SERIAL PRIMARY KEY, total NUMERIC(10,2));'
    ].join('\n');

    fakeGen.queueResponse(brokenDdl);
    fakeGen.queueResponse(fixedDdl);

    const projRes = await app.inject({
      method: 'POST',
      url: '/api/baselines/BASE-ORDER-001/projections',
      payload: {
        artifactType: 'sql-schema'
      }
    });

    expect(projRes.statusCode).toBe(200);
    const body = projRes.json();
    const validatedDto = ProjectionRecordDtoSchema.parse(body);

    expect(validatedDto.content).toBe(fixedDdl);
    expect(validatedDto.metadata.measuredVerification.repairsNeeded).toBe(1);
    expect(validatedDto.metadata.measuredVerification.attemptCount).toBe(2);
  });

  it('discovers product ambiguity as CandidateFinding and blocks successor baseline creation until human reconciliation (CONSUMER-69-AC-3, AC-4, AC-6)', async () => {
    // 1. Create initial baseline BASE-AUTH-001
    const req = await seedAuditedRequirement(
      'REQ-AUTH-001',
      'REQ-AUTH-001-R1',
      'User logs into the platform'
    );

    await app.inject({
      method: 'POST',
      url: '/api/baselines',
      payload: {
        id: 'BASE-AUTH-001',
        requirementRevisions: [req.id],
        createdBy: 'LEAD'
      }
    });

    // 2. Generator encounters product ambiguity (multiple active sessions)
    const ddlWithFinding = [
      '-- @baseline BASE-AUTH-001',
      '-- @requirements REQ-AUTH-001-R1',
      '-- @finding: undefined-cardinality | Unclear whether a user can hold multiple concurrent active sessions',
      'CREATE TABLE sessions (',
      '  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
      '  user_id TEXT NOT NULL,',
      '  token TEXT NOT NULL',
      ');'
    ].join('\n');

    fakeGen.queueResponse(ddlWithFinding);

    const projRes = await app.inject({
      method: 'POST',
      url: '/api/baselines/BASE-AUTH-001/projections',
      payload: {
        artifactType: 'sql-schema'
      }
    });
    expect(projRes.statusCode).toBe(200);

    // 3. Verify CandidateFinding is saved in repository with disposition OPEN and affectedRequirementRevisions populated
    const findings = await repo.listCandidateFindings();
    const discovered = findings.find((f) => f.type === 'undefined-cardinality');
    expect(discovered).toBeDefined();
    expect(discovered?.disposition).toBe('OPEN');
    expect(discovered?.discoveredBy).toBe('artifact-validation');
    expect(discovered?.affectedRequirementRevisions).toEqual(['REQ-AUTH-001-R1']);

    // 4. Attempt to create successor baseline BASE-AUTH-002 with the same requirement: MUST FAIL CLOSED with BLOCKED_BY_OPEN_FINDINGS
    const blockedRes = await app.inject({
      method: 'POST',
      url: '/api/baselines',
      payload: {
        id: 'BASE-AUTH-002',
        requirementRevisions: [req.id],
        createdBy: 'LEAD'
      }
    });

    expect(blockedRes.statusCode).toBe(409);
    const blockedBody = blockedRes.json();
    expect(blockedBody.code).toBe('BLOCKED_BY_OPEN_FINDINGS');
    expect(blockedBody.details.blockingFindings).toHaveLength(1);
    expect(blockedBody.details.blockingFindings[0].findingId).toBe(discovered!.id);

    // 5. Human operator reconciles the finding via disposition endpoint
    const resolveRes = await app.inject({
      method: 'POST',
      url: `/api/findings/${discovered!.id}/disposition`,
      payload: {
        disposition: 'RESOLVED',
        rationale:
          'Architecture decision: single active session per user enforced by token invalidation on login.'
      }
    });
    expect(resolveRes.statusCode).toBe(200);

    // 6. Retry creating successor baseline BASE-AUTH-002: now succeeds!
    const successorRes = await app.inject({
      method: 'POST',
      url: '/api/baselines',
      payload: {
        id: 'BASE-AUTH-002',
        requirementRevisions: [req.id],
        createdBy: 'LEAD'
      }
    });
    expect(successorRes.statusCode).toBe(200);
    const successorBaseline = RequirementsBaselineDtoSchema.parse(successorRes.json());
    expect(successorBaseline.id).toBe('BASE-AUTH-002');
  });

  it('records technical choices as non-authoritative PROPOSED engineering decisions (CONSUMER-69-AC-2)', async () => {
    const req = await seedAuditedRequirement(
      'REQ-TECH-001',
      'REQ-TECH-001-R1',
      'Store customer feedback comments'
    );

    await app.inject({
      method: 'POST',
      url: '/api/baselines',
      payload: {
        id: 'BASE-TECH-001',
        requirementRevisions: [req.id],
        createdBy: 'LEAD'
      }
    });

    const ddlWithDecision = [
      '-- @baseline BASE-TECH-001',
      '-- @requirements REQ-TECH-001-R1',
      '-- @decision: GIN index on comment text | Optimize full-text search over customer feedback',
      'CREATE TABLE feedback (',
      '  id SERIAL PRIMARY KEY,',
      '  comments TEXT NOT NULL',
      ');',
      "CREATE INDEX idx_feedback_comments ON feedback USING gin(to_tsvector('english', comments));"
    ].join('\n');

    fakeGen.queueResponse(ddlWithDecision);

    const projRes = await app.inject({
      method: 'POST',
      url: '/api/baselines/BASE-TECH-001/projections',
      payload: {
        artifactType: 'sql-schema'
      }
    });
    expect(projRes.statusCode).toBe(200);

    // Verify the proposed decision is recorded with state PROPOSED
    const decisions = await repo.listEngineeringDecisions({
      baselineId: createRequirementsBaselineId('BASE-TECH-001')
    });
    expect(decisions).toHaveLength(1);
    expect(decisions[0].statement).toBe('GIN index on comment text');
    expect(decisions[0].rationale).toBe('Optimize full-text search over customer feedback');
    expect(decisions[0].state).toBe('PROPOSED');
  });

  it('guarantees historical immutability of projections and durability across restarts (CONSUMER-69-AC-5, AC-7)', async () => {
    const req = await seedAuditedRequirement(
      'REQ-IMMUT-001',
      'REQ-IMMUT-001-R1',
      'Store products in catalog'
    );

    await app.inject({
      method: 'POST',
      url: '/api/baselines',
      payload: {
        id: 'BASE-IMMUT-001',
        requirementRevisions: [req.id],
        createdBy: 'LEAD'
      }
    });

    const ddl = [
      '-- @baseline BASE-IMMUT-001',
      '-- @requirements REQ-IMMUT-001-R1',
      'CREATE TABLE products (id SERIAL PRIMARY KEY, name TEXT NOT NULL);'
    ].join('\n');

    fakeGen.setDefaultResponse(ddl);

    const projRes = await app.inject({
      method: 'POST',
      url: '/api/baselines/BASE-IMMUT-001/projections',
      payload: {
        artifactType: 'sql-schema'
      }
    });
    expect(projRes.statusCode).toBe(200);
    const proj = projRes.json();

    // 1. Attempting to overwrite the projection record in repository throws ImmutableRecordConflictError
    const existingRecord = await repo.getProjectionRecord(proj.id);
    expect(existingRecord).toBeDefined();

    await expect(repo.saveProjectionRecord(existingRecord!)).rejects.toThrow(
      ImmutableRecordConflictError
    );

    // 2. Re-instantiate repository from disk to simulate process restart
    const restartedRepo = new FilesystemRequirementsRepository({ baseDir: tempDir });
    const reloaded = await restartedRepo.getProjectionRecord(proj.id);
    expect(reloaded).toBeDefined();
    expect(reloaded?.id).toBe(proj.id);
    expect(reloaded?.baselineId).toBe('BASE-IMMUT-001');
    expect(reloaded?.content).toBe(ddl);
    expect(reloaded?.metadata.measuredVerification.contentHash).toBe(
      proj.metadata.measuredVerification.contentHash
    );
  });
});
